// Options page logic (§7, §12): the enrollment settings + the execute_js opt-in.
//
// Every setting lives in chrome.storage.local (per-profile, NEVER in the bundle):
//   allowExecuteJs — the authoritative execute_js gate (§12), default OFF
//   serviceAddress — the wss/ws service URL (the shared token is gone, §7)
//   browserName    — the suggested_title source shown to the operator
//   enrollCode     — the ~10-min window code, submitted once to enroll
// installUuid is read-only here (generated by the SW); its first INSTALL_UUID_PREFIX_LEN
// (18) chars let the operator find THEIR request in the admin list — NOT 8, see the
// constant below for why the shorter prefix was unsafe. The enroll state is fetched from
// the SW's get_connection_state (durable-fact derived, §7). Kept in an external
// module because the extension_pages CSP forbids inline scripts.
//
// Pure helpers are exported for unit tests; DOM wiring runs only in a document.

// Storage keys — mirror src/constants.js (options.js is loaded raw in the page, not
// bundled, so it does not import to avoid module-resolution surprises under the CSP).
const ALLOW_EXECUTE_JS_KEY = "allowExecuteJs";
const SERVICE_ADDRESS_KEY = "serviceAddress";
const BROWSER_NAME_KEY = "browserName";
const ENROLL_CODE_KEY = "enrollCode";
const INSTALL_UUID_KEY = "installUuid";

// Mirrors src/constants.js INSTALL_UUID_PREFIX_LEN — and, crucially, the /admin console
// (templates/app.js), which must print the SAME number of chars: the operator's whole job
// here is to compare the string on this page with a row in that list.
const INSTALL_UUID_PREFIX_LEN = 18;

// The operator identifies their own request by this prefix of installUuid (§7). NOT the
// first 8 chars: two browsers of the same person carry the same suggested title and the
// same uniform origin, so an 8-char prefix is the ONLY discriminator left — and it is
// short enough to collide in a fleet, which means approving the wrong install.
export function installUuidPrefix(uuid) {
  return typeof uuid === "string" && uuid ? uuid.slice(0, INSTALL_UUID_PREFIX_LEN) : "—";
}

// --- the service-address gate (§7) -----------------------------------------
// KEEP IN SYNC with extension/src/service-address.js — that file carries the rationale
// (option A puts the RAW secret on the wire, so TLS is the only thing hiding it, so a
// `ws://`/`http://` address is refused rather than hinted at). The check is duplicated
// because this page is loaded raw under the extension_pages CSP and imports nothing;
// test/options.test.js runs BOTH implementations over the same table so they cannot drift.
const LOOPBACK_HOSTS = ["localhost", "127.0.0.1", "[::1]"];

export function serviceAddressError(raw) {
  const value = typeof raw === "string" ? raw.trim() : "";
  if (!value) return "empty";
  let url;
  try {
    url = new URL(value);
  } catch {
    return "malformed";
  }
  if (!url.hostname) return "malformed";
  if (url.protocol === "wss:") return null;
  if (url.protocol === "ws:") {
    return LOOPBACK_HOSTS.includes(url.hostname) ? null : "insecure";
  }
  if (url.protocol === "http:" || url.protocol === "https:") return "http-scheme";
  return "malformed";
}

// The refusal reason, spelled out for the operator. "Saved" is not an option for a
// rejected address: silently keeping it would leave the field looking accepted.
export function addressErrorText(code) {
  switch (code) {
    case "insecure":
      return (
        "Refused: ws:// is unencrypted, so this instance's secret and the enrollment " +
        "code would travel in the clear. Use wss:// (ws:// is allowed only for " +
        "localhost / 127.0.0.1)."
      );
    case "http-scheme":
      return "Refused: this is the WebSocket address of the service — use wss://, not http(s)://.";
    case "empty":
      return "Enter the service address first (wss://host).";
    case "malformed":
    default:
      return "Refused: the address must look like wss://host[:port].";
  }
}

// A human label for an enroll state (§7). Unknown/empty reads as "не зарегистрирован".
// A pending state carrying an enroll_rejected `reject` shows WHY instead of an eternal
// "waiting for approval" (bad_code/closed/capacity/…), so the operator re-stages a code.
export function enrollLabel(state, reject) {
  if (reject && (state === "pending" || state === "needs-enroll")) {
    return "заявка отклонена: " + reject;
  }
  // QUARANTINE gets its own line because `getEnrollState` resolves `quarantined` BEFORE
  // `pending`: a quarantined instance still holds a valid old secret, so its state is
  // never `pending` and the reject above would never be reached on the one path that
  // cannot recover by itself. A terminal reject (bad_code / closed) wipes the staged
  // code, the probe stops asking, and nothing moves until the operator types a fresh
  // one — which the label has to say, or the screen keeps reading "требуется повторная
  // регистрация" over an attempt that already came back rejected.
  if (reject && state === "quarantined") {
    return "заявка отклонена: " + reject + " — введите новый код регистрации";
  }
  switch (state) {
    case "approved":
      return "одобрен";
    case "pending":
      return "ожидает одобрения";
    case "revoked":
      return "отозван";
    case "quarantined":
      return "неизвестный инстанс — требуется повторная регистрация";
    case "needs-enroll":
    default:
      return "не зарегистрирован";
  }
}

// --- DOM wiring (browser only) ---------------------------------------------
export async function init(doc, chromeApi) {
  const el = (id) => doc.getElementById(id);
  const status = el("status");
  const setStatus = (t) => {
    if (status) status.textContent = t;
  };

  const checkbox = el("allow-execute-js");
  const addressInput = el("service-address");
  const nameInput = el("browser-name");
  const codeInput = el("enroll-code");
  const submitBtn = el("submit-enroll");
  const uuidOut = el("install-uuid");
  const stateOut = el("enroll-state");

  // Load current values.
  const got = await chromeApi.storage.local.get([
    ALLOW_EXECUTE_JS_KEY,
    SERVICE_ADDRESS_KEY,
    BROWSER_NAME_KEY,
    ENROLL_CODE_KEY,
    INSTALL_UUID_KEY,
  ]);
  if (checkbox) checkbox.checked = !!got[ALLOW_EXECUTE_JS_KEY];
  if (addressInput) addressInput.value = got[SERVICE_ADDRESS_KEY] || "";
  if (nameInput) nameInput.value = got[BROWSER_NAME_KEY] || "";
  if (codeInput) codeInput.value = got[ENROLL_CODE_KEY] || "";
  if (uuidOut) uuidOut.textContent = installUuidPrefix(got[INSTALL_UUID_KEY]);

  // Enroll state from the SW (durable-fact derived, §7). `addressError` is reported here
  // too: a profile whose stored address predates this gate (or a bundle bootstrap with a
  // ws:// serviceUrl) is refused by the SW, and the operator must see WHY rather than an
  // address that is filled in but does nothing.
  try {
    const st = await chromeApi.runtime.sendMessage({ type: "get_connection_state" });
    if (stateOut) stateOut.textContent = enrollLabel(st && st.enrollState, st && st.enrollReject);
    if (st && st.addressError) setStatus(addressErrorText(st.addressError));
  } catch {
    if (stateOut) stateOut.textContent = enrollLabel(null);
  }

  // Persist-on-change for the plain settings.
  if (checkbox) {
    checkbox.addEventListener("change", async () => {
      await chromeApi.storage.local.set({ [ALLOW_EXECUTE_JS_KEY]: checkbox.checked });
      setStatus(checkbox.checked ? "execute_js enabled on this copy" : "execute_js disabled on this copy");
    });
  }
  if (addressInput) {
    addressInput.addEventListener("change", async () => {
      const value = addressInput.value.trim();
      // An empty field is a legitimate "not configured yet" — store it (clearing the
      // setting) without shouting. Anything else must pass the scheme gate BEFORE it is
      // persisted: a stored ws:// address is not a warning to act on later, it is the
      // exact state in which the next hello publishes the secret.
      const error = value ? serviceAddressError(value) : null;
      if (error) {
        setStatus(addressErrorText(error));
        return;
      }
      await chromeApi.storage.local.set({ [SERVICE_ADDRESS_KEY]: value });
      setStatus(value ? "Service address saved" : "Service address cleared");
    });
  }
  if (nameInput) {
    nameInput.addEventListener("change", async () => {
      await chromeApi.storage.local.set({ [BROWSER_NAME_KEY]: nameInput.value.trim() });
      setStatus("Browser name saved");
    });
  }
  if (codeInput) {
    codeInput.addEventListener("change", async () => {
      await chromeApi.storage.local.set({ [ENROLL_CODE_KEY]: codeInput.value.trim() });
    });
  }

  // Submit enrollment: persist the code, then ask the SW to send the enroll_request
  // with it now (§7 / acc 5).
  if (submitBtn) {
    submitBtn.addEventListener("click", async () => {
      const code = codeInput ? codeInput.value.trim() : "";
      if (!code) {
        setStatus("Enter the enrollment code first");
        return;
      }
      // Submitting against a refused (or missing) address would send the one-time window
      // code and the fresh secret nowhere — or, without the gate, into the clear. Refuse
      // here too: the address field may hold an unsaved value the change handler rejected.
      const addressError = serviceAddressError(addressInput ? addressInput.value : "");
      if (addressError) {
        setStatus(addressErrorText(addressError));
        return;
      }
      submitBtn.disabled = true;
      // Persist the (validated) address together with the code: the operator may have
      // typed both and clicked straight through, and the SW resolves the address from
      // storage, not from this page.
      await chromeApi.storage.local.set({
        [SERVICE_ADDRESS_KEY]: addressInput.value.trim(),
        [ENROLL_CODE_KEY]: code,
      });
      try {
        const res = await chromeApi.runtime.sendMessage({ type: "submit_enrollment", code });
        // "Submitted" is a claim about US, not about the service: the socket may not have
        // opened at all. Say what actually happens — the request is re-sent until the
        // service confirms it (connection.js `_sendOpening`) — so a silent "waiting for
        // approval" over a request nobody received is not what the operator reads.
        setStatus(
          res && res.ok
            ? "Enrollment sent — it is re-sent automatically until the service confirms it"
            : "Submit failed" + (res && res.error ? ": " + res.error : ""),
        );
        // Refresh the shown state.
        try {
          const st = await chromeApi.runtime.sendMessage({ type: "get_connection_state" });
          if (stateOut) stateOut.textContent = enrollLabel(st && st.enrollState, st && st.enrollReject);
        } catch {
          /* leave the prior label */
        }
      } catch (e) {
        setStatus("Submit failed: " + (e && e.message));
      } finally {
        submitBtn.disabled = false;
      }
    });
  }
}

// Auto-run in the extension page; never at import under vitest (node, no document).
if (typeof document !== "undefined" && document.getElementById("submit-enroll")) {
  init(document, chrome).catch((e) => console.error("[options]", e));
}
