// Options page logic (§7, §12): the enrollment settings + the execute_js opt-in.
//
// Every setting lives in chrome.storage.local (per-profile, NEVER in the bundle):
//   allowExecuteJs — the authoritative execute_js gate (§12), default OFF
//   serviceAddress — the wss/ws service URL (the shared token is gone, §7)
//   browserName    — the suggested_title source shown to the operator
//   enrollCode     — the ~10-min window code, submitted once to enroll
// installUuid is read-only here (generated by the SW); its first 8 chars let the
// operator find THEIR request in the admin list. The enroll state is fetched from
// the SW's get_connection_state (durable-fact derived, §7). Kept in an external
// module because the extension_pages CSP forbids inline scripts.
//
// Pure helpers are exported for unit tests; DOM wiring runs only in a document.

// Storage keys — mirror src/constants.js (options.js is loaded raw in the page, not
// bundled, so it does not import to avoid module-resolution surprises under the CSP).
const ALLOW_EXECUTE_JS_KEY = "allowExecuteJs";
const SERVICE_ADDRESS_KEY = "serviceAddress";
const BROWSER_NAME_KEY = "browserName";
const ENROLL_CODE_KEY = "enrollCode";
const INSTALL_UUID_KEY = "installUuid";

// The operator identifies their own request by the first 8 chars of installUuid (§7).
export function firstEight(uuid) {
  return typeof uuid === "string" && uuid ? uuid.slice(0, 8) : "—";
}

// A human label for an enroll state (§7). Unknown/empty reads as "не зарегистрирован".
// A pending state carrying an enroll_rejected `reject` shows WHY instead of an eternal
// "waiting for approval" (bad_code/closed/capacity/…), so the operator re-stages a code.
export function enrollLabel(state, reject) {
  if (reject && (state === "pending" || state === "needs-enroll")) {
    return "заявка отклонена: " + reject;
  }
  switch (state) {
    case "approved":
      return "одобрен";
    case "pending":
      return "ожидает одобрения";
    case "revoked":
      return "отозван";
    case "quarantined":
      return "неизвестный инстанс — требуется повторная регистрация";
    case "needs-enroll":
    default:
      return "не зарегистрирован";
  }
}

// --- DOM wiring (browser only) ---------------------------------------------
export async function init(doc, chromeApi) {
  const el = (id) => doc.getElementById(id);
  const status = el("status");
  const setStatus = (t) => {
    if (status) status.textContent = t;
  };

  const checkbox = el("allow-execute-js");
  const addressInput = el("service-address");
  const nameInput = el("browser-name");
  const codeInput = el("enroll-code");
  const submitBtn = el("submit-enroll");
  const uuidOut = el("install-uuid");
  const stateOut = el("enroll-state");

  // Load current values.
  const got = await chromeApi.storage.local.get([
    ALLOW_EXECUTE_JS_KEY,
    SERVICE_ADDRESS_KEY,
    BROWSER_NAME_KEY,
    ENROLL_CODE_KEY,
    INSTALL_UUID_KEY,
  ]);
  if (checkbox) checkbox.checked = !!got[ALLOW_EXECUTE_JS_KEY];
  if (addressInput) addressInput.value = got[SERVICE_ADDRESS_KEY] || "";
  if (nameInput) nameInput.value = got[BROWSER_NAME_KEY] || "";
  if (codeInput) codeInput.value = got[ENROLL_CODE_KEY] || "";
  if (uuidOut) uuidOut.textContent = firstEight(got[INSTALL_UUID_KEY]);

  // Enroll state from the SW (durable-fact derived, §7).
  try {
    const st = await chromeApi.runtime.sendMessage({ type: "get_connection_state" });
    if (stateOut) stateOut.textContent = enrollLabel(st && st.enrollState, st && st.enrollReject);
  } catch {
    if (stateOut) stateOut.textContent = enrollLabel(null);
  }

  // Persist-on-change for the plain settings.
  if (checkbox) {
    checkbox.addEventListener("change", async () => {
      await chromeApi.storage.local.set({ [ALLOW_EXECUTE_JS_KEY]: checkbox.checked });
      setStatus(checkbox.checked ? "execute_js enabled on this copy" : "execute_js disabled on this copy");
    });
  }
  if (addressInput) {
    addressInput.addEventListener("change", async () => {
      await chromeApi.storage.local.set({ [SERVICE_ADDRESS_KEY]: addressInput.value.trim() });
      setStatus("Service address saved");
    });
  }
  if (nameInput) {
    nameInput.addEventListener("change", async () => {
      await chromeApi.storage.local.set({ [BROWSER_NAME_KEY]: nameInput.value.trim() });
      setStatus("Browser name saved");
    });
  }
  if (codeInput) {
    codeInput.addEventListener("change", async () => {
      await chromeApi.storage.local.set({ [ENROLL_CODE_KEY]: codeInput.value.trim() });
    });
  }

  // Submit enrollment: persist the code, then ask the SW to send the enroll_request
  // with it now (§7 / acc 5).
  if (submitBtn) {
    submitBtn.addEventListener("click", async () => {
      const code = codeInput ? codeInput.value.trim() : "";
      if (!code) {
        setStatus("Enter the enrollment code first");
        return;
      }
      submitBtn.disabled = true;
      await chromeApi.storage.local.set({ [ENROLL_CODE_KEY]: code });
      try {
        const res = await chromeApi.runtime.sendMessage({ type: "submit_enrollment", code });
        setStatus(res && res.ok ? "Enrollment submitted — waiting for approval" : "Submit failed");
        // Refresh the shown state.
        try {
          const st = await chromeApi.runtime.sendMessage({ type: "get_connection_state" });
          if (stateOut) stateOut.textContent = enrollLabel(st && st.enrollState, st && st.enrollReject);
        } catch {
          /* leave the prior label */
        }
      } catch (e) {
        setStatus("Submit failed: " + (e && e.message));
      } finally {
        submitBtn.disabled = false;
      }
    });
  }
}

// Auto-run in the extension page; never at import under vitest (node, no document).
if (typeof document !== "undefined" && document.getElementById("submit-enroll")) {
  init(document, chrome).catch((e) => console.error("[options]", e));
}
